for number in range(1,10):
	print("*" * number,end="")
	print(" " * (10-number),end="")
	print("*" * (10-number),end="")
	print(" " * 2*number,end="")
	print("*" * (10-number),end="")
	print(" " * (10-number),end="")
	print("*" * number,end="")
	print("*" * number,end="")
	print(" " * (10-number),end="")
	print("*" * (10-number),end="")
	print(" " * 2*number,end="")
	print("*" * (10-number),end="")
	print(" " * (10-number),end="")
	print("*" * number)